import xarray as xr
import matplotlib.pyplot as plt
import numpy as np

a = xr.open_dataset("output2.nc")
b = xr.open_dataset("../radiances/job_panorama2/mc.rad.spc.nc")
c = xr.open_dataset("../radiances/job_flx/mc.flx.spc.nc")
#d = xr.open_dataset("rayli_panorama.nc")
#alt = xr.open_dataset("output2.nc")
groundbox = a["groundbox"][0,:].load().data.astype(int)

x = np.arange(1,91,1)
fig, ax = plt.subplots()

ax.plot(x,a["image"][0,:],".-b",label="Local estimates/Rayli")
ax.plot(x,b["radiance"][:,0,0,0,0,0], ".-r", label="Mystic panorama")
ax.plot(x,a["Ldown"][0,:], color = "k", label="ldown")
ax.plot(x,a["Ldown"][0,:]+a["Lup"][0,:], color="g", label="ldown+lup")
ax.fill_between(x, a["Ldown"][0,:], a["Ldown"][0,:]+a["Lup"][0,:],color="g")
ax.plot(x,a["Ldown"][0,:]+a["Lup"][0,:]+a["Ldir"][0,:],color="c", label="ldown+lup+ldir")
ax.fill_between(x, a["Ldown"][0,:]+a["Lup"][0,:], a["Ldown"][0,:]+a["Lup"][0,:]+a["Ldir"][0,:],color="c")
ax.plot(x,a["Ldown"][0,:]+a["Lup"][0,:]+a["Ldir"][0,:]+a["gRdir"][0,:], color="m", label="ldown+lup+ldir+gRdir")
ax.fill_between(x, a["Ldown"][0,:]+a["Lup"][0,:]+a["Ldir"][0,:], a["Ldown"][0,:]+a["Lup"][0,:]+a["Ldir"][0,:]+a["gRdir"][0,:],color="m" ) 
ax.plot(x,a["Ldown"][0,:]+a["Lup"][0,:]+a["Ldir"][0,:]+a["gRdir"][0,:]+a["gRdiff"][0,:] , color="y", label="ldown+lup+ldir+gRdir+grDiff")
ax.fill_between(x, a["Ldown"][0,:]+a["Lup"][0,:]+a["Ldir"][0,:]+a["gRdir"][0,:], a["Ldown"][0,:]+a["Lup"][0,:]+a["Ldir"][0,:]+a["gRdir"][0,:]+a["gRdiff"][0,:], color="y")
#ax.plot(np.arange(1,91,1),groundbox, label="groundbox index")
#ax.plot(np.arange(1,91,1),(c["Edir"][groundbox,0,0]+c["Edown"][groundbox,0,0])*0.2/np.pi , label="ground reflection")
#ax.plot(np.arange(1,91,1),(c["Edir"][groundbox,0,0])*0.2/np.pi , label="ground reflection Edir")
#ax.plot(np.arange(1,91,1),(c["Edown"][groundbox,0,0])*0.2/np.pi , label="ground reflection Edown")
#ax.plot(np.arange(1,91,1), d["transmissivity"][:,0]*1347.745/0.707, label="rayli panorama")
ax.set_xlabel("Pixel")
ax.set_ylabel("Radiance in W/sr/m²")
ax.set_xlim(0,90)
ax.legend()
plt.grid(True,linestyle=":")
plt.tight_layout()
plt.show()
